export type SenatorRow = {
  senator1: string;
  senator2: string;
  url1: string;
  url2: string;
};

export const senatorData: Record<string, SenatorRow> = {
  Alabama: {
    senator1: "Tommy Tuberville",
    url1: "https://www.tuberville.senate.gov/contact/contact-form/",
    senator2: "Katie Britt",
    url2: "https://www.britt.senate.gov/contact/contact-form/",
  },
  Alaska: {
    senator1: "Lisa Murkowski",
    url1: "https://www.murkowski.senate.gov/contact/email-lisa",
    senator2: "Dan Sullivan",
    url2: "https://www.sullivan.senate.gov/contact/email-dan",
  },
  Arizona: {
    senator1: "Mark Kelly",
    url1: "https://www.kelly.senate.gov/contact/contact-form/",
    senator2: "Ruben Gallego",
    url2: "https://www.gallego.senate.gov/contact/contact-form/",
  },
  Arkansas: {
    senator1: "John Boozman",
    url1: "https://www.boozman.senate.gov/public/index.cfm/email-john",
    senator2: "Tom Cotton",
    url2: "https://www.cotton.senate.gov/contact/contact-form/",
  },
  California: {
    senator1: "Alex Padilla",
    url1: "https://www.padilla.senate.gov/contact/contact-form/",
    senator2: "Adam Schiff",
    url2: "https://www.schiff.senate.gov/contact/contact-form/",
  },
  Colorado: {
    senator1: "Michael Bennet",
    url1: "https://www.bennet.senate.gov/public/index.cfm/contact",
    senator2: "John Hickenlooper",
    url2: "https://www.hickenlooper.senate.gov/contact/contact-form/",
  },
  Connecticut: {
    senator1: "Chris Murphy",
    url1: "https://www.murphy.senate.gov/contact/contact-form/",
    senator2: "Richard Blumenthal",
    url2: "https://www.blumenthal.senate.gov/contact/contact-form/",
  },
  Delaware: {
    senator1: "Tom Carper",
    url1: "https://www.carper.senate.gov/contact/contact-form/",
    senator2: "Chris Coons",
    url2: "https://www.coons.senate.gov/contact/contact-form/",
  },
  Florida: {
    senator1: "Marco Rubio",
    url1: "https://www.rubio.senate.gov/public/index.cfm/contact",
    senator2: "Rick Scott",
    url2: "https://www.rickscott.senate.gov/contact/contact-form/",
  },
  Georgia: {
    senator1: "Jon Ossoff",
    url1: "https://www.ossoff.senate.gov/contact/contact-form/",
    senator2: "Raphael Warnock",
    url2: "https://www.warnock.senate.gov/contact/contact-form/",
  },
  Hawaii: {
    senator1: "Brian Schatz",
    url1: "https://www.schatz.senate.gov/contact/contact-form/",
    senator2: "Mazie Hirono",
    url2: "https://www.hirono.senate.gov/contact/contact-form/",
  },
  Idaho: {
    senator1: "Mike Crapo",
    url1: "https://www.crapo.senate.gov/contact/contact-form/",
    senator2: "Jim Risch",
    url2: "https://www.risch.senate.gov/public/index.cfm/contact-form",
  },
  Illinois: {
    senator1: "Dick Durbin",
    url1: "https://www.durbin.senate.gov/contact/contact-form/",
    senator2: "Tammy Duckworth",
    url2: "https://www.duckworth.senate.gov/contact/contact-form/",
  },
  Indiana: {
    senator1: "Todd Young",
    url1: "https://www.young.senate.gov/contact/contact-form/",
    senator2: "Mike Braun",
    url2: "https://www.braun.senate.gov/contact/contact-form/",
  },
  Iowa: {
    senator1: "Chuck Grassley",
    url1: "https://www.grassley.senate.gov/contact/contact-form/",
    senator2: "Joni Ernst",
    url2: "https://www.ernst.senate.gov/contact/contact-form/",
  },
  Kansas: {
    senator1: "Jerry Moran",
    url1: "https://www.moran.senate.gov/public/index.cfm/contactjerry",
    senator2: "Roger Marshall",
    url2: "https://www.marshall.senate.gov/contact/contact-form/",
  },
  Kentucky: {
    senator1: "Mitch McConnell",
    url1: "https://www.mcconnell.senate.gov/public/index.cfm/contactform",
    senator2: "Rand Paul",
    url2: "https://www.paul.senate.gov/contact/contact-form/",
  },
  Louisiana: {
    senator1: "Bill Cassidy",
    url1: "https://www.cassidy.senate.gov/contact/contact-form/",
    senator2: "John Kennedy",
    url2: "https://www.kennedy.senate.gov/public/index.cfm/contact-form",
  },
  Maine: {
    senator1: "Susan Collins",
    url1: "https://www.collins.senate.gov/contact/contact-form/",
    senator2: "Angus King",
    url2: "https://www.king.senate.gov/contact/contact-form/",
  },
  Maryland: {
    senator1: "Ben Cardin",
    url1: "https://www.cardin.senate.gov/contact/contact-form/",
    senator2: "Chris Van Hollen",
    url2: "https://www.vanhollen.senate.gov/contact/contact-form/",
  },
  Massachusetts: {
    senator1: "Elizabeth Warren",
    url1: "https://www.warren.senate.gov/contact/contact-form/",
    senator2: "Ed Markey",
    url2: "https://www.markey.senate.gov/contact/contact-form/",
  },
  Michigan: {
    senator1: "Debbie Stabenow",
    url1: "https://www.stabenow.senate.gov/contact/contact-form/",
    senator2: "Gary Peters",
    url2: "https://www.peters.senate.gov/contact/contact-form/",
  },
  Minnesota: {
    senator1: "Amy Klobuchar",
    url1: "https://www.klobuchar.senate.gov/public/index.cfm/contact",
    senator2: "Tina Smith",
    url2: "https://www.smith.senate.gov/contact/contact-form/",
  },
  Mississippi: {
    senator1: "Roger Wicker",
    url1: "https://www.wicker.senate.gov/contact/contact-form/",
    senator2: "Cindy Hyde-Smith",
    url2: "https://www.hydesmith.senate.gov/contact/contact-form/",
  },
  Missouri: {
    senator1: "Josh Hawley",
    url1: "https://www.hawley.senate.gov/contact/contact-form/",
    senator2: "Eric Schmitt",
    url2: "https://www.schmitt.senate.gov/contact/contact-form/",
  },
  Montana: {
    senator1: "Jon Tester",
    url1: "https://www.tester.senate.gov/contact/contact-form/",
    senator2: "Steve Daines",
    url2: "https://www.daines.senate.gov/connect/contact-steve",
  },
  Nebraska: {
    senator1: "Deb Fischer",
    url1: "https://www.fischer.senate.gov/public/index.cfm/contact",
    senator2: "Pete Ricketts",
    url2: "https://www.ricketts.senate.gov/contact/contact-form/",
  },
  Nevada: {
    senator1: "Catherine Cortez Masto",
    url1: "https://www.cortezmasto.senate.gov/contact/contact-form/",
    senator2: "Jacky Rosen",
    url2: "https://www.rosen.senate.gov/contact/contact-form/",
  },
  "New Hampshire": {
    senator1: "Jeanne Shaheen",
    url1: "https://www.shaheen.senate.gov/contact/contact-form/",
    senator2: "Maggie Hassan",
    url2: "https://www.hassan.senate.gov/contact/contact-form/",
  },
  "New Jersey": {
    senator1: "Bob Menendez",
    url1: "https://www.menendez.senate.gov/contact/contact-form/",
    senator2: "Cory Booker",
    url2: "https://www.booker.senate.gov/contact/contact-form/",
  },
  "New Mexico": {
    senator1: "Martin Heinrich",
    url1: "https://www.heinrich.senate.gov/contact/contact-form/",
    senator2: "Ben Ray Lujan",
    url2: "https://www.lujan.senate.gov/contact/contact-form/",
  },
  "New York": {
    senator1: "Chuck Schumer",
    url1: "https://www.schumer.senate.gov/contact/contact-form/",
    senator2: "Kirsten Gillibrand",
    url2: "https://www.gillibrand.senate.gov/contact/contact-form/",
  },
  "North Carolina": {
    senator1: "Thom Tillis",
    url1: "https://www.tillis.senate.gov/contact/contact-form/",
    senator2: "Ted Budd",
    url2: "https://www.budd.senate.gov/contact/contact-form/",
  },
  "North Dakota": {
    senator1: "John Hoeven",
    url1: "https://www.hoeven.senate.gov/contact/contact-form/",
    senator2: "Kevin Cramer",
    url2: "https://www.cramer.senate.gov/contact/contact-form/",
  },
  Ohio: {
    senator1: "Sherrod Brown",
    url1: "https://www.brown.senate.gov/contact/contact-form/",
    senator2: "JD Vance",
    url2: "https://www.vance.senate.gov/contact/contact-form/",
  },
  Oklahoma: {
    senator1: "James Lankford",
    url1: "https://www.lankford.senate.gov/contact/contact-form/",
    senator2: "Markwayne Mullin",
    url2: "https://www.mullin.senate.gov/contact/contact-form/",
  },
  Oregon: {
    senator1: "Ron Wyden",
    url1: "https://www.wyden.senate.gov/contact/contact-form/",
    senator2: "Jeff Merkley",
    url2: "https://www.merkley.senate.gov/contact/contact-form/",
  },
  Pennsylvania: {
    senator1: "Bob Casey",
    url1: "https://www.casey.senate.gov/contact/contact-form/",
    senator2: "John Fetterman",
    url2: "https://www.fetterman.senate.gov/contact/contact-form/",
  },
  "Rhode Island": {
    senator1: "Jack Reed",
    url1: "https://www.reed.senate.gov/contact/contact-form/",
    senator2: "Sheldon Whitehouse",
    url2: "https://www.whitehouse.senate.gov/contact/contact-form/",
  },
  "South Carolina": {
    senator1: "Lindsey Graham",
    url1: "https://www.lgraham.senate.gov/public/index.cfm/contact-form",
    senator2: "Tim Scott",
    url2: "https://www.scott.senate.gov/contact/contact-form/",
  },
  "South Dakota": {
    senator1: "John Thune",
    url1: "https://www.thune.senate.gov/public/index.cfm/contact-form",
    senator2: "Mike Rounds",
    url2: "https://www.rounds.senate.gov/contact/contact-form/",
  },
  Tennessee: {
    senator1: "Lamar Alexander",
    url1: "https://www.alexander.senate.gov/public/index.cfm/tell-me-your-thoughts",
    senator2: "Bill Hagerty",
    url2: "https://www.hagerty.senate.gov/contact/contact-form/",
  },
  Texas: {
    senator1: "John Cornyn",
    url1: "https://www.cornyn.senate.gov/contact/contact-form/",
    senator2: "Ted Cruz",
    url2: "https://www.cruz.senate.gov/public/index.cfm/contact-form",
  },
  Utah: {
    senator1: "Mike Lee",
    url1: "https://www.lee.senate.gov/contact/contact-form/",
    senator2: "Mitt Romney",
    url2: "https://www.romney.senate.gov/contact/contact-form/",
  },
  Vermont: {
    senator1: "Bernie Sanders",
    url1: "https://www.sanders.senate.gov/contact/contact-form/",
    senator2: "Peter Welch",
    url2: "https://www.welch.senate.gov/contact/contact-form/",
  },
  Virginia: {
    senator1: "Mark Warner",
    url1: "https://www.warner.senate.gov/public/index.cfm/contact",
    senator2: "Tim Kaine",
    url2: "https://www.kaine.senate.gov/contact/contact-form/",
  },
  Washington: {
    senator1: "Patty Murray",
    url1: "https://www.murray.senate.gov/contact/contact-form/",
    senator2: "Maria Cantwell",
    url2: "https://www.cantwell.senate.gov/contact/contact-form/",
  },
  "West Virginia": {
    senator1: "Joe Manchin",
    url1: "https://www.manchin.senate.gov/contact/contact-form/",
    senator2: "Shelley Moore Capito",
    url2: "https://www.capito.senate.gov/contact/contact-form/",
  },
  Wisconsin: {
    senator1: "Ron Johnson",
    url1: "https://www.ronjohnson.senate.gov/contact/contact-form/",
    senator2: "Tammy Baldwin",
    url2: "https://www.baldwin.senate.gov/contact/contact-form/",
  },
  Wyoming: {
    senator1: "John Barrasso",
    url1: "https://www.barrasso.senate.gov/public/index.cfm/contact-form",
    senator2: "Cynthia Lummis",
    url2: "https://www.lummis.senate.gov/contact/contact-form/",
  },
};
